### ISSUE TITLE
Ability to pull specific issues from non-tracked repos

### ISSUE THREAD

**Issue by gms8994** [ralphbean/bugwarrior#725] opened 2020-04-15 20:01 UTC
I've created issues in other repositories (that I don't necessarily have commit access to) that I'd like to follow within bugwarrior (for example, I want to keep tabs on any updates to the issue that are made - perfect example... this issue heh).

Is there a way to do this, or is this even a feature that someone else might want?

**Comment by bbigras** [comment] 2021-11-25 00:10
Oh, I definitely want this. Did anyone check if it would be easy to implement?

**Comment by ryneeverett** [comment] 2021-11-29 02:01
It would be a fair amount of work. The service api would probably need to be extended (across every service) to add a method for pulling a single given issue. We'd probably need to do our best based on api documentation since nobody has an account with all the services. I'd expect there to be some services which we can't even fathom a guess on so there'd need to be an error message when this feature isn't supported by a given service.

**Comment by ryneeverett** [comment] 2022-04-24 02:22
Duplicate of #516.

**Closed as completed by ryneeverett** 2022-04-24 02:22 UTC
Labels: feature proposal
