### ISSUE TITLE
[Github]: Bugwarrior pulls all my issues from github, except only those from organization/repo

### ISSUE THREAD

**Issue by offlinehacker** [ralphbean/bugwarrior#455] opened 2017-03-14 10:39 UTC
## Description

I want only issues from GateHubNet user and only from microkit repo to be pulled, but bugwarrior pulls all issues from all projects.

## Version

Bugwarrior from git master.

## Config

```
[general]
targets = my_github
inline_links = False
annotation_links = True
legacy_matching=False
log.level = DEBUG

[hooks]

[my_github]
service = github
default_priority = H
add_tags = open_source
github.username = GateHubNet
github.login = offlinehacker
github.include_user_repos = False
github.include_repos = microkit
github.token = <token>
```

## Output

```
root@0ad61dbb6556:/# bugwarrior-pull
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 1 workers.
INFO:my_github|Working on [my_github]
DEBUG:my_github| Found 15 issues.
DEBUG:my_github| Pruned down to 15 issues.
INFO:my_github|Done with [my_github] in 11.689074s
INFO:bugwarrior|Done aggregating remote issues.
INFO:db|Adding 15 tasks
INFO:db|Adding task (bw)Is#6 - Describe project internals for deve
INFO:db|Adding task (bw)Is#10 - Create sphinx extension directive f
INFO:db|Adding task (bw)Is#14 - Add support for execution of domain
INFO:db|Adding task (bw)Is#6 - Update ubuntu tasks
INFO:db|Adding task (bw)Is#10 - api/swagger: lazy load swagger api-
INFO:db|Adding task (bw)Is#10 - Option to select how much you want
INFO:db|Adding task (bw)Is#5 - Support for healthcheck services
INFO:db|Adding task (bw)PR#1 - knex implementation
INFO:db|Adding task (bw)Is#3 - Create sphinx documentation
INFO:db|Adding task (bw)Is#9 - Add support for generating tests on
INFO:db|Adding task (bw)Is#4 - Create color burst phase and freque
INFO:db|Adding task (bw)PR#9 - add support for JWT on request and
INFO:db|Adding task (bw)Is#8 - Microkit express JWT
INFO:db|Adding task (bw)Is#5 - Create new example, with new config
INFO:db|Adding task (bw)Is#2 - Generate more optimally with tests
INFO:db|Updating 0 tasks
INFO:db|Closing 0 tasks
```

Only issues 5, 7, 8, 13 should be pulled.

Update: I have tried with latest release, same result.

**Comment by gdetrez** [comment] 2017-03-14 22:57
Is it possible that the extra issues are all assigned to the user offlinehacker?
In that case, you can try `github.include_user_issues = False` to disable pulling assigned issues.

**Comment by offlinehacker** [comment] 2017-03-18 18:49
@gdetrez no, adding this flag did not do anything, no filtering seems to be applied, still i get all issues that are assigned to me on all groups.

**Comment by jamur2** [comment] 2017-03-20 17:16
I ran into a similar issue with pull requests, and based on https://github.com/ralphbean/bugwarrior/pull/389 I updated `get_pulls` as well:

```
diff --git a/bugwarrior/services/github.py b/bugwarrior/services/github.py
index b3fada4..790f0ef 100644
--- a/bugwarrior/services/github.py
+++ b/bugwarrior/services/github.py
@@ -55,7 +55,7 @@ class GithubClient(ServiceClient):
         return self._getter(url)

     def get_pulls(self, username, repo):
-        tmpl = "https://api.github.com/repos/{username}/{repo}/pulls?per_page=100"
+        tmpl = "https://api.github.com/repos/{username}/{repo}/pulls?state=open&per_page=100"
         url = tmpl.format(username=username, repo=repo)
         return self._getter(url)
```

Not sure of the broader impacts, but it seemed to behave better for me (although if the issue is specifically issues and not PRs, weird that https://github.com/ralphbean/bugwarrior/pull/389 wouldn't have fixed it).

EDIT: On further inspection, this looks unrelated, feel free to disregard.

**Comment by gdetrez** [comment] 2017-03-24 22:43
@offlinehacker just to make sure, you tried the `github.include_user_issues` on master (it wasn't available in the last release)?

**Comment by mrVanDalo** [comment] 2019-12-26 21:02
Same issue here, every year I check if this behavior is fixed, but still not the case. :(

my config contains 
```
github.involved_issues = True
github.exclude_repos = some_repo
github.include_user_repos = False
github.include_user_issues = False
```

And I still get everything from `some_repo`. I thought `exclude_repos` are a filter.

**Comment by ryneeverett** [comment] 2022-04-03 03:12
Not sure what the situation was 5 years ago but I believe this is now perhaps just a matter of confusing documentation. In order to achieve the desired behavior, do not set `include_user_repos = False`, which prevents issues being fetched from `username`. Example on the current `develop` branch:

```ini
[general]
targets = my_github

[my_github]
service = github
github.login = ryneeverett
github.token = <token>
github.username = xtruder
github.include_repos = kubenix
```

```shell
$ bugwarrior-pull
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [my_github]
INFO:bugwarrior.services:Done with [my_github] in 1.160941s
INFO:bugwarrior.services:Done aggregating remote issues.
INFO:bugwarrior.db:Adding 14 tasks
INFO:bugwarrior.db:Adding task (bw)Is#33 - kubernetes 1.22 support? .. https://github.com/xtruder/kubenix/issues/33
INFO:bugwarrior.db:Adding task (bw)Is#31 - How to override a generated kubernetes definition value type? .. https://github.com/xtruder/kubenix/issues/31
INFO:bugwarrior.db:Adding task (bw)PR#29 - K3s .. https://github.com/xtruder/kubenix/pull/29
INFO:bugwarrior.db:Adding task (bw)PR#28 - Nix flake .. https://github.com/xtruder/kubenix/pull/28
INFO:bugwarrior.db:Adding task (bw)Is#26 - Rejuventate with kustomize White Box Application concept .. https://github.com/xtruder/kubenix/issues/26
INFO:bugwarrior.db:Adding task (bw)Is#23 - Implement more examples .. https://github.com/xtruder/kubenix/issues/23
INFO:bugwarrior.db:Adding task (bw)Is#22 - Support for efficient copy of multiple docker images using skopeo .. https://github.com/xtruder/kubenix/issues/22
INFO:bugwarrior.db:Adding task (bw)Is#19 - Loading custom resource definitions from yaml .. https://github.com/xtruder/kubenix/issues/19
INFO:bugwarrior.db:Adding task (bw)PR#18 - wip k3s support .. https://github.com/xtruder/kubenix/pull/18
INFO:bugwarrior.db:Adding task (bw)Is#17 - Flaky tests .. https://github.com/xtruder/kubenix/issues/17
INFO:bugwarrior.db:Adding task (bw)Is#14 - Name configMaps after a path in Nix store, just likeyou do for docker images .. https://github.com/xtruder/kubenix/issues/14
INFO:bugwarrior.db:Adding task (bw)Is#9 - Kubenix refactoring .. https://github.com/xtruder/kubenix/issues/9
INFO:bugwarrior.db:Adding task (bw)Is#8 - feedback .. https://github.com/xtruder/kubenix/issues/8
INFO:bugwarrior.db:Adding task (bw)Is#6 - Wrong version for ClusterRoleBinding .. https://github.com/xtruder/kubenix/issues/6
INFO:bugwarrior.db:Updating 0 tasks
INFO:bugwarrior.db:Closing 0 tasks
(bugwarrior) bugwarrior upstream/dev
```

**Comment by mrVanDalo** [comment] 2022-04-18 14:16
For me this is actually fixed. I'm using the `query` parameter with github, and so far it works for me.

**Comment by ryneeverett** [comment] 2022-04-18 14:36
Yeah, the `query` parameter gives you a lot of flexibility but I think this issue was about achieving this with the options available before `query` was introduced -- an issue which has also been fixed.

**Closed** 2022-04-18 14:38 UTC
Labels: bug, github, documentation
