### ISSUE TITLE
 Automatically set projects for Phabricator

### ISSUE THREAD

**Issue by ghost** [ralphbean/bugwarrior#559] opened 2018-05-08 07:45 UTC
It would be nice if Bugwarrior would automatically synchronise the projects of a task with what it finds in Phabricator.

**Comment by urzds** [comment] 2018-05-18 10:02
This is actually a bug, not a feature proposal. The cause was that the `projects` list was never populated, and hence the section name / target was always used.

#566 implicitly fixes that for the most common cases, if `include_sub_projects` is enabled, since it will populate `projects` with the projects bugwarrior is subscribed to via `project_phids`. To fix the case where `project_phids` is not set, `projects` should also be populated in that case. There currently is no PR open which does that.

#565 adds an option to prevent #566's code from setting random projects, in case the task / diff is tagged with multiple projects.

**Comment by ralphbean** [comment] 2019-08-03 21:15
Closing as @ghost is now a deleted user.

**Closed by ralphbean** 2019-08-03 21:15 UTC
Labels: bug, phabricator
