### ISSUE TITLE
Completed tasks are ignored

### ISSUE THREAD

**Issue by telenieko** [ralphbean/bugwarrior#658] opened 2019-05-08 20:41 UTC
Hi,

Sample workflow:
- I receive an email, put "TODO" label
- gmail service in bugwarrior pulls that email (query = label:TODO)
- I complete the task
- gmail service pulls the email again

As far as I understand the code, this is due bugwarrior only considering tasks which are either pending or waiting, but not completed (db.py, find_local_uuid also get_managed_task_uuids)

But this means that one has to complete the task and remove the label between two runs of bugwarrior. Am I correct?

If you remove the label first only, the task is deleted. If you mark completed first, the task is duplicated.

Shouldn't bugwarrior consider completed tasks also (only in find_local_uuid I think)?

Or, is something wrong in my workflow? 

I am running from the develop branch.

**Comment by telenieko** [comment] 2019-05-09 18:09
I have done this:

```
diff --git a/bugwarrior/db.py b/bugwarrior/db.py
index df10c26..2b64a68 100644
--- a/bugwarrior/db.py
+++ b/bugwarrior/db.py
@@ -190,6 +190,7 @@ def find_local_uuid(tw, keys, issue, legacy_matching=False):
                 'or': [
                     ('status', 'pending'),
                     ('status', 'waiting'),
+                    ('status', 'completed')
                 ],
             })
```

As a test, and it works properly for gmail (issues are properly updated if still labelled instead of duplicated).

But I have no idea on what sideeffects that could have on other services ?

**Comment by ralphbean** [comment] 2019-08-03 18:54
Ah, this is kind of intentional.

Consider the use case where you're working with a bug tracker, instead of gmail.

* The issue is opened.
* It is pulled to taskwarrior by github.
* The issue is closed in the tracker.
* Either bugwarrior closes it for you locally, or you mark it as done yourself.
* Later, the issue is re-opened!
* Bugwarrior opens a new task for you to see this.

I think people (including myself) expect bugwarrior to do this for them, so that they can catch situations like this.

In your case, if you mark a email with TODO and bugwarrior pulls it, you should be able to remove the TODO label after which point bugwarrior will mark it as "done" locally (it shouldn't delete it, to my knowledge).

WDYT?

**Comment by TheNeuralBit** [comment] 2019-09-19 16:08
It seems that bugwarrior just needs to be opinionated about which list (the tracker, or your local tw db) is the source of truth since it can get into these ambiguous situations, and it's been decided that the external tracker is the SoT (which makes sense!).

I agree with @telenieko though that it would be nice if I could mark a task done locally and have the tracker updated (e.g. remove the TODO label for me). Maybe a solution could be a hook that makes the appropriate API call when I close a task that was added by bugwarrior.

**Comment by process0** [comment] 2019-09-25 02:52
@ralphbean Is this behavior in the docs?  Until experiencing this, I assumed that bugwarrior would ignore differences between the local taskwarrior and the external tracker regarding its state since bugwarrior has no "push" component (what @TheNeuralBit is referring to).  

I think it might be useful to have it as an option for those who have bugwarrior-pull on a cron, and want to resolve tasks between the local tw and external tracker at the end of the day.

**Comment by ryneeverett** [comment] 2022-04-21 18:14
As of #779 bugwarrior will reopen previously closed tasks rather than opening a new one. I think that's about as good a compromise as we're going to get given the varying concerns raised here. I'm not opposed to continuing the discussion here but given this change I think a new issue with a more concrete proposal might be more productive.

**Closed by ryneeverett** 2022-04-21 18:14 UTC
Labels: feature proposal, documentation
