### ISSUE TITLE
Redmine pull close task if redmine-user unassigned

### ISSUE THREAD

**Issue by rndmh3ro** [ralphbean/bugwarrior#521] opened 2017-11-05 18:22 UTC
Hi! I just found out about this project and I'm liking it so far!
Here's my problem:

I'm importing issues from Redmine that are assigned to me. This works great.
If I assign an issue to another person in redmine and run `bugwarrior-pull`, the corresponding task gets closed.
Then if I get the same issue assigned to me again and then run `bugwarrior-pull` a new task is created. The old task is not used anymore.

My expectation is that the same task is used again and no new one is created.
Is my expectation wrong here?

Thanks!

**Comment by ryneeverett** [comment] 2021-01-16 06:09
Looks like a #769 was a duplicate of this one. It has been fixed in the 1.8.0 release.

**Closed by ryneeverett** 2021-01-16 06:09 UTC
Labels: bug, redmine
