### ISSUE TITLE
Fails to add issue "Cannot subtract strings"

### ISSUE THREAD

**Issue by d3zd3z** [ralphbean/bugwarrior#699] opened 2019-12-02 16:52 UTC
When pulling https://github.com/JuulLabs-OSS/mcuboot/issues/529, bugwarrior reports an error, and fails to add this particular issue:

```
INFO:bugwarrior.db:Adding task (bw)Is#529 - MCUBoot not cleaning up properly be .. https://github.com/JuulLabs-OSS/mcuboot/issues/529
ERROR:bugwarrior.db:Unable to add task: b'Configuration override rc.json.array:TRUE\nConfiguration override rc.verbose:new-uuid\nConfiguration override rc.confirmation:no\nConfiguration override rc.dependency.confirmation:no\nConfiguration override rc.uda.githubtitle.type:string\nConfiguration override rc.uda.githubtitle.label:"Github Title"\nConfiguration override rc.uda.githubbody.type:string\nConfiguration override rc.uda.githubbody.label:"Github Body"\nConfiguration override rc.uda.githubcreatedon.type:date\nConfiguration override rc.uda.githubcreatedon.label:"Github Created"\nConfiguration override rc.uda.githubupdatedat.type:date\nConfiguration override rc.uda.githubupdatedat.label:"Github Updated"\nConfiguration override rc.uda.githubclosedon.type:date\nConfiguration override rc.uda.githubclosedon.label:"GitHub Closed"\nConfiguration override rc.uda.githubmilestone.type:string\nConfiguration override rc.uda.githubmilestone.label:"Github Milestone"\nConfiguration override rc.uda.githubrepo.type:string\nConfiguration override rc.uda.githubrepo.label:"Github Repo Slug"\nConfiguration override rc.uda.githuburl.type:string\nConfiguration override rc.uda.githuburl.label:"Github URL"\nConfiguration override rc.uda.githubtype.type:string\nConfiguration override rc.uda.githubtype.label:"Github Type"\nConfiguration override rc.uda.githubnumber.type:numeric\nConfiguration override rc.uda.githubnumber.label:"Github Issue/PR #"\nConfiguration override rc.uda.githubuser.type:string\nConfiguration override rc.uda.githubuser.label:"Github User"\nConfiguration override rc.uda.githubnamespace.type:string\nConfiguration override rc.uda.githubnamespace.label:"Github Namespace"\nConfiguration override rc.uda.githubstate.type:string\nConfiguration override rc.uda.githubstate.label:"GitHub State"\nCannot subtract strings'
Traceback (most recent call last):
  File "/home/davidb/.local/lib/python3.7/site-packages/bugwarrior/db.py", line 422, in synchronize
    new_task = tw.task_add(**issue)
  File "/home/davidb/.local/lib/python3.7/site-packages/taskw/warrior.py", line 683, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/home/davidb/.local/lib/python3.7/site-packages/taskw/warrior.py", line 476, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <unprintable TaskwarriorError object>
```

I think this comes from the reporter (or commenter) having a hyphen in their name.

**Comment by d3zd3z** [comment] 2019-12-11 19:02
I don't think it is just the hyphen in the name. I see many other issues and pull requests that have hyphens and pull in without problem.

**Comment by ryneeverett** [comment] 2022-04-23 02:21
#733 appears to be a duplicate of this `<unprintable TaskwarriorError object>` exception. However, I'm going to close this one because there's more information there.

**Closed as completed by ryneeverett** 2022-04-23 02:21 UTC
Labels: bug, github
