### ISSUE TITLE
MultipleMatches exception raised when running against Taskwarrior 2.6.0

### ISSUE THREAD

**Issue by JoshMock** [ralphbean/bugwarrior#841] opened 2021-10-05 19:11 UTC
I upgraded Taskwarrior to 2.6.0 this morning and started getting the following error on every run of `bugwarrior-pull`:

```
bugwarrior.db.MultipleMatches: Issue ___ matched multiple IDs: {...}
```

Appears to be triggered by the following lines in `find_taskwarrior_uuid`:

https://github.com/ralphbean/bugwarrior/blob/a37d861a7a703c558c93de19bdad6bf2e6c77d6e/bugwarrior/db.py#L203-L209

I don't know enough about Taskwarrior internals to know how UUIDs work or might have changed, but I do know this was a fairly significant update from them.

Bugwarrior: 1.8.0
Taskwarrior: 2.6.0
OS: Arch Linux

Issue is not present after downgrading back to Taskwarrior 2.5.3.

I may start to investigate this myself and see if I can contribute a solution, but it may not be timely enough if lots of folks experience this after upgrading.

**Comment by tbabej** [comment] 2021-10-05 21:47
Hey @JoshMock, I believe the problem is that `bugwarrior` uses `taskw` under the hood, which is currently incompatible with the 2.6.0 release :crying_cat_face: 

The good news there is already PR (pending review) to fix this, that we were hoping could get merged before the 2.6.0 release, but it's better late than never :pray: 

https://github.com/ralphbean/taskw/pull/152

You can install this directly from my branch using:

`pip3 install -U git+git://github.com/tbabej/taskw@develop`

**Comment by JoshMock** [comment] 2021-10-05 21:59
Thanks so much @tbabej! I will try this soon.

**Comment by tbabej** [comment] 2021-10-09 17:49
Alright, ralphbean/taskw#152 has been merged, so I believe this issue should be fixed on the `develop` branch of `taskw` now (install via `pip3 install -U git+git://github.com/ralphbean/taskw@develop`)

**Comment by ryneeverett** [comment] 2021-10-18 22:41
Closing for now since this seems to be a duplicate of #840.

**Closed as completed by ryneeverett** 2021-10-18 22:41 UTC
Labels: bug

**Comment by srl295** [comment] 2021-11-02 21:46
Confirmed that ralphbean/taskw@3baf339370c7cb4c62d52cb6736ed0cb458a57b5 solves this issue.
