### ISSUE TITLE
connecting to Phabricator without Maniphest

### ISSUE THREAD

**Issue by swills** [ralphbean/bugwarrior#595] opened 2018-07-25 12:25 UTC
Similar to #576 if you try to connect to a Phabricator instance which doesn't have Maniphest, but instead only has Differential, you get:

APIError: ERR-CONDUIT-CALL: Method 'maniphest.query' belongs to application 'Maniphest', which is not installed.

Could bugwarrior handle this and still allow adding tasks to Taskwarrior for the Differential reviews?

**Comment by ryneeverett** [comment] 2022-04-17 14:22
This is starting to look stale. Perhaps we should just document the limitation and close until somebody wants to address it.

**Comment by ryneeverett** [comment] 2022-06-08 15:19
Actually looks like #607 was a duplicate of this and it was resolved in #608.

**Closed by ryneeverett** 2022-06-08 15:19 UTC
Labels: feature proposal, phabricator, documentation
