### ISSUE TITLE
Fail if one of the services failed

### ISSUE THREAD

**Issue by Lykos153** [ralphbean/bugwarrior#1017] opened 2023-10-30 16:01 UTC
Due to the limitations in the gitlab API, I have configured multiple instances of the same gitlab repo to sync all MRs and issues I am interested in. When one of them fails to pull (eg. due to bad connection or today's gitlab availability issues), bugwarrior closes all respective tasks in taskwarrior. They do get re-opened once all pulls succeed during a consecutive run, but it would be nice to have the option to just fail the whole run in such cases.

An alternative would be to expose metrics from the pull to the `pre_import` hook, so it can decide whether to fail or not.

**Comment by ryneeverett** [comment] 2023-10-30 17:26
Are you using the latest release (1.8.0) or the develop branch?

Related and/or duplicate issues: #897 and #866.

**Comment by Lykos153** [comment] 2023-10-30 17:49
I'm on 15ac6a2197f490db3cf9b5a4a934b5a41804ce76

**Comment by ryneeverett** [comment] 2024-01-02 20:36
Triage:

- It *seemed* like we finally got the logic right in #825 and even added a regression test which *should* show that this specific issue is fixed. However, this issue, along with #866, draws that premise into question.
- I'm inclined to call this a duplicate of #866 since that issue includes logs which make resolution more plausible.

**Comment by ryneeverett** [comment] 2024-02-16 21:48
I reviewed #866 and the sync logic again and still don't see how this behavior is possible. The message `f"Aborted [{target}] due to critical error."` is logged in `collect.py`, indicating bugwarrior is aware that the service failed. In `db.py`, the tasks to close are a subset of the tasks that did not fail.

To be clear, aborting the pull when one service fails is not ideal behavior and I don't want to revert to that unless there is compelling evidence that it is necessary. If you or anyone else has logs or insights into how this is possible I'd be happy to reconsider.

**Closed as completed by ryneeverett** 2024-02-16 21:48 UTC
Labels: bug
