### ISSUE TITLE
[jira] comment.author.name - object has no attribute name

### ISSUE THREAD

**Issue by dkuku** [ralphbean/bugwarrior#748] opened 2020-08-19 09:00 UTC
Thats my error 
```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.                                             
INFO:bugwarrior.services:Spawning 1 workers.         
INFO:bugwarrior.services:Working on [DEV]            
INFO:bugwarrior.services.jira:Found 1 distinct sprint fields.                                             
ERROR:bugwarrior.services:Worker for [DEV] failed: <class 'jira.resources.UnknownResource'> object has no attribute 'name' ('UnknownResource' object is not subscriptable)
Traceback (most recent call last):                   
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/jira/resources.py", line 161, in __getattr__
    return self[item]                                
TypeError: 'UnknownResource' object is not subscriptable                                                  

During handling of the above exception, another exception occurred:                                       

Traceback (most recent call last):                   
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():                   
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/bugwarrior/services/jira.py", line 352, in issues
    'annotations': self.annotations(case, issue)     
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/bugwarrior/services/jira.py", line 330, in annotations
    return self.build_annotations(                   
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/bugwarrior/services/__init__.py", line 149, in build_annotations
    for author, message in annotations:              
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/bugwarrior/services/jira.py", line 332, in <genexpr>
    comment.author.name,                             
  File "/home/kuku/Projects/.direnv/python-3.8.5/lib/python3.8/site-packages/jira/resources.py", line 177, in __getattr__
    raise AttributeError("%r object has no attribute %r (%s)" % (self.__class__, item, e))                
AttributeError: <class 'jira.resources.UnknownResource'> object has no attribute 'name' ('UnknownResource' object is not subscriptable)
INFO:bugwarrior.services:Done with [DEV] in 2.262059s                                                     
INFO:bugwarrior.services:Terminating workers     
```
all keys on my `comment.__dict__`
`['_resource', '_options', '_session', '_base_url', 'raw', 'self', 'accountId', 'avatarUrls', 'displayName', 'active', 'timeZone', 'accountType']`
my updated code
```
        return self.build_annotations(
            ((
                comment.author.displayName
                comment.body
            ) for comment in comments),
            issue_obj.get_processed_url(issue_obj.get_url())
        )
```

**Comment by ryneeverett** [comment] 2020-08-19 13:52
Duplicate of #718. This is resolved in master but we haven't had a release since then.

**Closed as completed by ryneeverett** 2020-08-19 13:52 UTC
Labels: bug, jira
